### ISSUE TITLE
dataplicity stop working

### ISSUE THREAD

**Issue by almirus** [AlexxIT/Dataplicity#30]
```
2024-09-18 11:11:08.318 ERROR (m2m) [agent] unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. device is offline")
2024-09-18 11:11:14.260 ERROR (m2m) [agent] unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. device is offline")
2024-09-18 11:11:20.271 ERROR (m2m) [agent] unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. device is offline")
2024-09-18 11:11:26.207 ERROR (m2m) [agent] unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. device is offline")
2024-09-18 11:11:32.180 ERROR (m2m) [agent] unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. device is offline")
2024-09-18 11:11:36.203 ERROR (m2m) [agent] unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. device is offline")
2024-09-18 11:11:38.193 ERROR (m2m) [agent] unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. device is offline")
2024-09-18 11:11:42.266 ERROR (m2m) [agent] unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. device is offline")
2024-09-18 11:11:44.133 ERROR (m2m) [agent] unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. device is offline")
2024-09-18 11:11:49.039 ERROR (m2m) [agent] unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. device is offline")
2024-09-18 11:11:51.130 ERROR (m2m) [agent] unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. device is offline")
2024-09-18 11:11:55.045 ERROR (m2m) [agent] unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. device is offline")
2024-09-18 11:11:57.142 ERROR (m2m) [agent] unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. device is offline")
2024-09-18 11:12:01.220 ERROR (m2m) [agent] unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. device is offline")
2024-09-18 11:12:03.175 ERROR (m2m) [agent] unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. device is offline")
```

**Comment by Smandurlo** [comment]
they started a massive migration: https://status.dataplicity.com/

It should return online by itself... hopefully. My servers are offline at the moment.

**Comment by Smandurlo** [comment]
yes, I read it too... but still nothing works :-( I have some uptimerobot sensors checking my dataplicity servers and, time to time, they get online for a couple of minutes, but not usable. I really don't know if the problem is the dns propagation and we still need to wait.

**Comment by Smandurlo** [comment]
Fonte: /usr/local/lib/python3.12/site-packages/dataplicity/client.py:308
Prima occorrenza: 09:36:23 (571 occorrenze)
Ultima registrazione: 10:41:38

    unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. device is offline")
    unable to associate m2m identity ("device.check_auth"=429, "Too many requests: 300 reqs/ 300 in 10 seconds")
    unable to associate m2m identity ("m2m.associate"=-32603, "Internal error. unable to connect to 'https://m2m.dataplicity.com/m2m/devices/a9263fbf-26af-4de0-a25b-4a18a3b54b8b/'; HTTPSConnectionPool(host='eu.m2m.dataplicity.com', port=443): Read timed out. (read timeout=10)")

**Comment by Smandurlo** [comment]
look this: one looks like it is online, but it doesn't load the dashboard. The other dataplicity servers are offline.

![dataplicity](https://github.com/user-attachments/assets/9c878824-18a8-4aeb-8a2f-d233a47dd100)

**Comment by Smandurlo** [comment]
this is the incident log
![incident](https://github.com/user-attachments/assets/68d10916-99f9-43af-afdd-d4eb4ed2c1d9)

**Comment by Smandurlo** [comment]
connected for 2 minutes

![incident](https://github.com/user-attachments/assets/bd2c30e9-d26f-454f-9a24-52f2d5618772)

 now offline again.

**Comment by alancik80** [comment]
I have the same problem.

**Comment by Smandurlo** [comment]
I can confirm it is a problem on their side.  I was able to connect to one of my server and work on it for some minutes, but now it is again offline. So, the component works.

**Comment by alancik80** [comment]
https://status.dataplicity.com/

**Comment by Smandurlo** [comment]
Investigation has determined that some corners of the internet were running a longer DNS TTL than we had anticipated.  A workaround has been put in place for the next few days while we wait for any remaining systems to catch up.

**Comment by Phobos1979** [comment]
Hi, I have the same problem from yesterday...
My homeassistant goes online but I can't open the dashboard and I can't connect to homeassistant server by dataplicity site :(
Hope they'll solve soon the problem

**Comment by almirus** [comment]
new error
```
2024-09-18 20:31:11.065 ERROR (dataplicity) [agent] sync failed unable to contact JSONRPC server 'https://api.dataplicity.com' (HTTP Error 502: Bad Gateway)
2024-09-18 20:32:53.838 ERROR (MainThread) [custom_components.dataplicity.utils] Can't register dataplicity device: 500
```

**Comment by Smandurlo** [comment]
It is extremely slow. So slow that almost everything times out while waiting for a response. It's not just a DNS problem. I can see some Home Assistant servers online, but the dashboards are not fully loading.

**Comment by alancik80** [comment]
My HA receives data from mobile devices. I receive geodata, sensor status.. But the mobile devices themselves do not have access to my HA. One-way data transfer :(
I suspect the problem may be in the wormhole.

**Comment by firstcolle** [comment]
hi, i have the same problem..
just to investigate, where do you run your home assistant?

**Comment by Smandurlo** [comment]
This night I was able to see a couple of HA servers loading, but very slowly. Now again they are offline.

The migration was a disaster

**Comment by Smandurlo** [comment]
but the Wormhole is not working. It doesn't connect to the server.


![dataplicity](https://github.com/user-attachments/assets/97e4591f-9099-43c3-a816-d11c83b08195)

**Comment by Smandurlo** [comment]
and DNS problem too

![dataplicity2](https://github.com/user-attachments/assets/6c2b5b63-0926-4ccf-9595-3119aa0dd1a7)

**Comment by Spiderandroid** [comment]
ciao raga.
e io che ho perso la testa convito fosse un problema di hassio.

ancora niente?
a me continua a non funzionare.

**Comment by Phobos1979** [comment]
> ciao raga. e io che ho perso la testa convito fosse un problema di hassio.
> 
> ancora niente? a me continua a non funzionare.

Non me ne parlare vah! 😂 
Stavo per buttare tutto all'aria, aggiornato, riavviato, reinstallato dataplicity su HA, poi una vocina mi ha detto di cercare su internet se qualcuno stava riscontrando gli stessi problemi ed eccomi qui.

**Comment by Spiderandroid** [comment]
Stessa trafila mia 😂🙈

Il giorno ven 20 set 2024 alle 00:19 Phobos1979 ***@***.***>
ha scritto:

**Comment by emanueledonatoni** [comment]
Anch'io lo stesso problema.
Qualcuno sa se è un problema che riguarda solo la zona Italia?

**Comment by alancik80** [comment]
No, the problem does not depend on the region.
Everything started working fine for me last night. But this morning it doesn't work again.
I don't understand what they are doing there, but it is unprofessional.

**Comment by Smandurlo** [comment]
The main problem is they started this migration without sending any advice before and they are not communicating anything since 18th

**Comment by pelik911** [comment]
Hoping that the problem was fixed, just in case, I removed Dataplicity from HACS and installed it again, but it does not appear in the list of integrations, neither from the browser nor in the application. I cleared the cache - it didn't help. Not only have I been unable to access the server remotely for three days, but now I don’t even have the opportunity to try it again. Help

**Comment by Spiderandroid** [comment]
Ora sta funzionando 🙏🏼🙏🏼 🤞 🤞

Il giorno ven 20 set 2024 alle 12:37 pelik911 ***@***.***> ha
scritto:

**Comment by firstcolle** [comment]
It's working for me now as well.

**Comment by Smandurlo** [comment]
@Spiderandroid @emanueledonatoni @Phobos1979 vi siete accorti che qui si scrive in inglese? Perché dobbiamo farci sempre riconoscere? :faceplam:

Some of my servers are back up, others are still not available

**Comment by emanueledonatoni** [comment]
My HA is still disconnected. However, I don't understand why there are so few reports online. It seems to be an issue limited to a few users.

**Comment by Phobos1979** [comment]
Now it's working for me!!!!

**Comment by Phobos1979** [comment]
> @Spiderandroid @emanueledonatoni @Phobos1979 vi siete accorti che qui si scrive in inglese? Perché dobbiamo farci sempre riconoscere? :faceplam:
> 
> Some of my servers are back up, others are still not available

Chiedo scusa, era solo un momento per scambiare due battute con un connazionale, tutto qui.

**Comment by Smandurlo** [comment]
I have still some HA servers offline. Maybe it is time to write to their customer service

**Comment by almirus** [comment]
Today everything finally worked properly.

**Comment by Smandurlo** [comment]
I still have some servers offline

**Comment by emanueledonatoni** [comment]
I still have HA disconnected as well.

**Comment by emanueledonatoni** [comment]
I configured a new device with a new token. Now everything works.

**Comment by Gferretta** [comment]
Hi
Yesterday worked fine.
Today i has no acceso again saddly
:(

**Comment by Smandurlo** [comment]
I have more than 20 HA servers running dataplicity... 1 is still offline

Dataplicity status:
 "Resolved - We have not had any indications of stability issues for the past few days and believe the issue is now closed.

Please contact our support line should you continue to experience any issues.
Sep 22, 00:14 UTC "

Going to write an email to the customer service

**Comment by Smandurlo** [comment]
Everything offline again. This is getting serious...

**Comment by firstcolle** [comment]
offline again..

**Comment by AlexxIT** [comment]
The problem is not relevant
