### ISSUE TITLE
Service fail yet again

### ISSUE THREAD

**Issue by fx-host-assistant** [AlexxIT/Dataplicity#37]
hi, my dataplicity home assistant servers are offline from this nigh, 3a.m. central europe timezone. Do you confirm? The dataplicity status page has no warnings, everything is working for them

**Comment by grandetype** [comment]
I have the same issue

**Comment by standhaftsohnsergius** [comment]
Hey guys, I'm having the same issue today. Maybe someone can suggest alternatives to Dataplicity for HA? Something with backup functionality would be great.

**Comment by iereus** [comment]
same problem, HA is offline today

**Comment by fx-host-assistant** [comment]
Ok, we are in this together 😁 I hope they will eventually notice the problem...

**Comment by Alexandrus17** [comment]
Damn, I've been trying to figure out what the problem is for hours now. I have already completely reinstalled Dataplicity several times. And now I accidentally found this topic. I hope they fix it!

**Comment by mexadm** [comment]
I have the same problem. Any news?

**Comment by Spiderandroid** [comment]
idem

**Comment by JSferry** [comment]
Same problem, from today morning.

**Comment by firstcolle** [comment]
Same here. Dataplicity homepage does not report any problem

**Comment by AlexxIT** [comment]
This is known problem from many users.

**Comment by standhaftsohnsergius** [comment]
> This is known problem from many users.

Hey bro, could you tell me where this is written and what we should do?

**Comment by Andrei33AV** [comment]
Добрый день! Вчера утром обнаружил, что удаленка не работает как решить проблему?

**Comment by AlexxIT** [comment]
It's written here, as you can see. And in other chats.
You can change the external access method in HA to a more stable one. Or just wait when Dataplicity service fix this issue.

**Comment by standhaftsohnsergius** [comment]
> It's written here, as you can see. And in other chats. You can change the external access method in HA to a more stable one. Or just wait when Dataplicity service fix this issue.

Is Nabu Casa more stable?

**Comment by AlexxIT** [comment]
I don't know. Never used it. Personally I think you can trust the authors of HA.

**Comment by Grigorij-Dudnik** [comment]
Hey,

Here is Grigorij from Dataplicity. Thanks for your reports. We noticed a server-related problem within Dataplicity, which we are solving already to make your devices work as soon as possible. Our apologizes for inconvinience.

**Comment by mexadm** [comment]
Thanks @Grigorij-Dudnik .

**Comment by Grigorij-Dudnik** [comment]
Some of the devices should work already. Rest of them should start working very soon, unless we'll not face other surprises in meanwhile.

**Comment by firstcolle** [comment]
i can confirm that now it is fully working

many thanks

**Comment by mexadm** [comment]
I also confirm that it works now. Thanks a lot!!

**Comment by Grigorij-Dudnik** [comment]
Glad to read it. If anything, let me know!

**Comment by Well902** [comment]
Привет. У меня проблема. Порт 80 закрыт. Проблема случилась вчера. Что делать?

**Comment by mexadm** [comment]
good morning! Same problem, today morning.

**Comment by BlackHorse83** [comment]
The problem has reoccurred. No access since this morning.

**Comment by Grigorij-Dudnik** [comment]
Ok, thanks for informing, checking what's going on

**Comment by mexadm** [comment]
any news?

**Comment by mexadm** [comment]
I want to share that after installing the 2025.4.0 (beta version), it seems that the problem has been resolved.

**Comment by AlexxIT** [comment]
This is not related to HA version

**Comment by Grigorij-Dudnik** [comment]
Most important of server problems been solved, but there some other appeared. Our apologizes for trouble. As previousely, we doing all to solve it.

**Comment by Leopoll** [comment]
The same problem. But the restarting of integration helped for some hour. Maybe we need to do automation in order to restart integration regularly?

**Comment by Grigorij-Dudnik** [comment]
@Leopoll It's not a case. Integration restart helped as it fastened flushing of old dnses after reparing our service, but after some time your agent most probably met other server error. So restarting agent helps to make device work again faster after server problems are solved, but does not solve server problems itself.

**Comment by Denis3d7** [comment]
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24 # 
    - 127.0.0.1/32   # Dataplicity

It's still working

**Comment by Akszyn** [comment]
> http: use_x_forwarded_for: true trusted_proxies: - 172.30.33.0/24 # - 127.0.0.1/32 # Dataplicity
> 
> It's still working

I don't think it makes a difference whether these addresses are added in the haos because there is a constant message that the device is offline anyway, and you have to restart the integration locally from time to time
